services:
  squid:
    container_name: squid
    environment:
      TZ: UTC
    ports:
      - "3128:3128"
    image: ubuntu/squid:5.2-22.04_beta
    networks:
      - proxy-net

networks:
  proxy-net:
    name: proxy-net
    external: true
